### PR TITLE
Add new packages

### PR DESCRIPTION
**Pull request by feimosi**

### CODE REVIEW

**Comment by inputsh** [comment]
Could you change the description of the Emmet package so it's a bit more descriptive? I seriously haven't understood what exactly does it do by reading the description you provided.

P.S. Could you also add a dot (`.`) at the end of the descriptions you've provided? I want to standardize the package description format a bit.

**Comment by feimosi** [comment]
No problem, I've just updated the description to be more informative.

**Comment by inputsh** [comment]
Thanks!

Since I accepted another pull request, do you want to create a new pull request or fix the conflicts in this one? Alternatively, I could create a pull request and incorporate your changes.

**Comment by feimosi** [comment]
I've just resolved all the conflicts here, although GitHub still shows you can't merge it.

**Comment by feimosi** [comment]
Ok, eventually I decided to create a new pull request #10. The easiest way.

**Pull request closed without merging**
