### PR TITLE
Added autocomplete-module-import

### PR DESCRIPTION
**Pull request by Shipow**
autocomplete-module-import
Search & install npm packages from import/require statements

### CODE REVIEW

**Comment by mehcode** [comment]
@Shipow This is pretty cool. 

If I were you I'd ask/beg/cajole https://github.com/spacegeek224/autocomplete-npm or atom devs if @spacegeek224 is unresponsive as that would be a much, much better name. Heck I'd even rename your package to `autocomplete-npm-plus` if all else fails.

I haven't tested it but I'd also work with https://atom.io/packages/autocomplete-modules to make sure your suggestions have less priority.

I won't ask you to do it in this PR but we do need an Autocomplete section if you want to set that up.

**Comment by Shipow** [comment]
Hey thanks, these are nice suggestions. We'll see what we can do. I'll keep you posted.

**Comment by FlorianWendelborn** [comment]
FYI the link is a 404. `atom-` should be removed. @Shipow @mehcode

**Comment by mehcode** [comment]
Hah. I guess that's what happens when I ignore the issue to add CI to this. Thanks for letting us know. Could you fix that @Shipow ?

**Comment by marisusis** [comment]
I was mentioned here, I haven't checked notifications for a while, is there anything I can do about the apm package?

**Comment by mehcode** [comment]
:wave: @spacegeek224 I actually don't know. I _think_ the only way to transfer ownership of a name is to transfer the repository itself. 

So steps for that would be:

1 - @spacegeek224 recreates https://github.com/spacegeek224/autocomplete-npm (yes I believe this step is necessary)
2 - @spacegeek224 [transfers the repository](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership) to @Shipow

**Comment by marisusis** [comment]
Sure!
Sorry I didn't see this earlier, I initially wanted to make my own autocomplete package, but then forgot about it.
I'd love to see a function npm autocomplete module in Atom!

**Comment by proudlygeek** [comment]
Hello everyone 👋 

I worked together with @Shipow on the autocomplete plugin, it would be really awesome to do this 👍 

@spacegeek224, could you transfer the repository to me (@proudlygeek) instead? 👼  

Thanks!

**Comment by marisusis** [comment]
I already transferred it to @Shipow xD

**Comment by Shipow** [comment]
@spacegeek224  Well I'm sorry but I missed the notification /o\

image

Would you do it again?
Thx \o/

**Pull request merged**
