### PR TITLE
Add link to themer tool.

### PR DESCRIPTION
**Pull request by mjswensen**
I know that the link doesn't follow the recommended format in CONTRIBUTING.md, but this is actually not an Atom package but rather a tool for generating Atom themes. I hope that's OK!

### CODE REVIEW

**Comment by mjswensen** [comment]
Bump 🙂

**Comment by inputsh** [comment]
While this is not a package, I would say that we should definitely include this, but maybe in a new category? @mehcode what do you think?

**Comment by mjswensen** [comment]
Monthly bump 😆 

@aleksandar-todorovic Happy to move it wherever you'd like.

**Comment by mehcode** [comment]
Eh. It's fine for now. If either of you have a better idea to categorize feel free to move it.

**Pull request merged**
