### PR TITLE
added chrome color picker

### PR DESCRIPTION
**Pull request by puranjayjain**
Why it's awesome?
It has built in palette
And will soon have the eyedropper functionality (without any external dependencies) :tada:

### CODE REVIEW

**Comment by mehcode** [comment]
It looks nice. But as this is a curated list we need to understand what makes it better than https://github.com/thomaslindstrom/color-picker (that has almost a million downloads).

**Comment by puranjayjain** [comment]
Well its actually a bit new (about the download count) 

Its actually written from scratch (using custom elements similar to atom) 

Covers the standard color formats used by web devs

It will have the colour picker from screen (anywhere) 

Built in palette (very demanded) 

More features coming soon (listed in milestones to make it more awesome) 

Loved by community

Try it and see for yourself!  ☺

**Comment by mehcode** [comment]
I'm going to caution you against putting too much functionality in a single package
- _Eye Dropper_ - This would be a nice package. Just this. And you'll have to integrate with something at the node level as this (to me) is only useful if it can pick colors from other applications.
- _Pick From Palette_ - I would much rather see an integration with Pigments and not arbitrarily saved colors (the latter being nice in a web app but this is an editor where you likely have a variables file with your palette).
- _Built-in Palette_ - I think you would see a lot more traction if you had a package that generated a bunch of color variables (SCSS / LESS / Stylus depending on file scope) from a chosen palette and source color (sort of like http://www.materialpalette.com/ but generating variables). Then a palette picker / pigments can work with it natively.

> Reading your milestones [...]
- _Color Conversion_ - This would be cool, but again, should be its own package. I'd grab and use this now as sometimes I'd like to do this (eg. convert from rgba to rgb or convert from hex to rgb). I'd just make it a select color text and use command `color-convert:to-rgb` or `color-convert:to-hex`, etc.

**Comment by puranjayjain** [comment]
@mehcode thanks for the suggestions. 
I'm was going to be working on the last one post 0.8.0. 
But making a separate packages doesn't cut it for me (after coming from vs studio enterprise then vs code then brackets). 
I wanted to create something that was familiar to users (like me)
I'll try to implement the pigments integration and open up my api too.
Also nice idea about the built in palette generation (for a new package)

**Comment by mehcode** [comment]
> But making a separate packages doesn't cut it for me (after coming from vs studio enterprise then vs code then brackets). 

That doesn't make sense (your reasoning). You can create a "virtual package" that installs a bunch of packages.

What I'm getting at is I have to reject this PR as we already have a color picker package. Yours would either need to extend the existing one (not replace, and then I'll wonder why you didn't make a PR into the existing color picker package) or be split up into different packages (so as not to rewrite the core color picker).

> The goal of any software should be to do one thing and do it well.

**Pull request closed without merging**
